### ISSUE TITLE
Add support for providing State from the config

### ISSUE THREAD

**Issue by imbradbrown** [okta/okta-sdk-appauth-android#32]
Working with a client who needs to provide values through State. Did not see a way to define this as OktaAppAuth line 487 does not expose the builder. 

Will be opening a PR for inclusion and would be grateful for feedback and if there is enough value to include.

**Comment by sergiymokiyenko-okta** [comment]
If I understand concept of the State correctly, that is a specific crypto-stable value that is added to every request in order to save client from man-in-the middle attacks. So I would rather keep it auto generated within library. 
But if your client needs to send additional parameters there is an option within OpenId protocol described here:
https://tools.ietf.org/html/rfc6749#section-11.2
Currently Okta's sdk does not support those parameters as well but I think adding this feature could be great and we can work on that.
What do you think @nbarbettini ?

**Comment by nbarbettini** [comment]
@sergiymokiyenko-okta The `state` parameter is sometimes used for that purpose, but technically can be any value that the client wants to send through the authorization server: https://tools.ietf.org/html/rfc6749#section-4.1.1
The authorization server must preserve the value and send it back unmodified.

The PKCE code_challenge and code_verifier will prevent a man-in-the-middle attack, because only the real client knows the plaintext of the code verifier.

What does this library send as `state` today?

**Comment by smokienko** [comment]
@nbarbettini Currently library uses internal implementation from AppAuth, but we can tweak that easily. AppAuth supports providing custom State as a part of AuthorizationRequest.
