### ISSUE TITLE
Please include Resource Owner Password Grant

### ISSUE THREAD

**Issue by vinliangx** [okta/okta-sdk-appauth-android#7]
Please include this feature as you have in iOS and JS...

**Comment by marklapasa** [comment]
+1

**Comment by nbarbettini** [comment]
We won't be adding the Resource Owner Password Grant (due to security issues, storing a `clientSecret` in your distributed binaries isn't good!) but we will add equivalent functionality.

See #37 for that work. We're working on this right now. If you want to be notified when it is released, watch #37. Thanks!
